services:
  - type: web
    name: tv-to-discord
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
